export const Strings = {
    tryThoseActivity: 'Try those activities daily to see long term improvements in your mental-health & productivity',
    setReminder:'Set Reminder',
    finishExercises:'Finish 3+ exercises today to stay calm and focused',
    peopleDoing:'2615 people doing sessions with you this hour',
    home: 'HOME',
    explore:'EXPLORE',
    care:'CARE',
    daily:'DAILY',
    profile:'PROFILE',
    yourAreas:'Your areas of growth are:',
    mentalWellbeing:'Mental Wellbeing',
    workLife:'Work-Life Balance',
    selfEfficacy:'Self Efficacy',
    outOf:'out of',
};
